### ISSUE TITLE
发送短信模块报错 BASE64Encoder 错误

### ISSUE THREAD

**Issue by techzhai** [aliyun/alibabacloud-sdk#394]
**1. 环境**
docker 环境 jdk11版本
```
<dependency>
            <groupId>com.aliyun</groupId>
            <artifactId>dysmsapi20170525</artifactId>
            <version>2.0.4</version>
</dependency>
```

**2. 报错栈信息**
Caused by: java.lang.NoClassDefFoundError: sun/misc/BASE64Encoder
        at com.aliyun.openapiutil.Client.getRPCSignature(Client.java:374)
        at com.aliyun.teaopenapi.Client.doRPCRequest(Client.java:154)
        at com.aliyun.dysmsapi20170525.Client.sendSmsWithOptions(Client.java:238)
        at com.aliyun.dysmsapi20170525.Client.sendSms(Client.java:243)

3. 具体报错位置 
   com.aliyun.openapiutil.Client类使用了jdk11里已经被废弃的 BASE64Encoder类，导致出现运行时报错

希望能早点修复，谢谢

**Comment by fengzehao** [comment]
同样的问题，我只能先降级了

**Comment by yndu13** [comment]
已修改，
diff:  https://github.com/aliyun/darabonba-openapi-util/commit/865c888518f409d8f2ec08ca9620dd45a912b7d6#diff-db8cdb300359b1afbb412addce71639d6ebdd0855b0bace8c3d08f586c2d0288
请将 SDK 升级到最新版试试

**Comment by fengzehao** [comment]
> 已修改， diff: [aliyun/darabonba-openapi-util@865c888#diff-db8cdb300359b1afbb412addce71639d6ebdd0855b0bace8c3d08f586c2d0288](https://github.com/aliyun/darabonba-openapi-util/commit/865c888518f409d8f2ec08ca9620dd45a912b7d6#diff-db8cdb300359b1afbb412addce71639d6ebdd0855b0bace8c3d08f586c2d0288) 请将 SDK 升级到最新版试试

https://github.com/aliyun/alibabacloud-java-sdk/blob/master/dysmsapi-20170525/pom.xml
中该库的依赖没有更新，所以还是不行，请协助更新此库pom文件
